version: "3"

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - fapi
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB' ]
      interval: 1s
      retries: 2
      timeout: 1s

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - fapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  migrations:
    build: .
    volumes:
      - .:/app
    command: alembic upgrade head
    env_file:
      - .env
    networks:
      - fapi

networks:
  fapi:
    external: true

volumes:
  pg_data: